kernel:
    resource: ../src/Kernel.php
    type: annotation

#general
basic:
    path: /
    controller: App\View\Home

OverOns:
    path: /OverOns
    controller: App\View\About

Behandelingen:
    path: /behandelingen
    controller: App\View\behandelingen

oauth2:
    resource: '@LeagueOAuth2ServerBundle/Resources/config/routes.php'
    type: php